teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 10              # Use the index that was observed as 1 in /joy
    enable_turbo_button: 9        # L1  <- hold for higher speed

    axis_linear:
      x: 1                        # Left stick vertical (up/down)
    scale_linear:
      x: 1.4                      # Normal max speed (m/s)
    scale_linear_turbo:
      x: 3.0

    axis_angular:
      yaw: 2                      # Left stick horizontal (left/right)
    scale_angular:
      yaw: 0.8
    scale_angular_turbo:
      yaw: 1.1